=== paullewallencom/oracle-978-1-8496-8454-5/_/Chapter 3/OCEPBook_Ch03_Spatial_EclipseProjects/com.oracle.cep.spatial.book.jaxb/schemas/shipdemo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://xmlns.oracle.com/ns/spatialdemo" xmlns:sd="http://xmlns.oracle.com/ns/spatialdemo" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<element name="ShipPosList" type="sd:ShipPositions"/>
	<element name="ShipPos" type="sd:ShipPosType"/>
	<element name="Alert" type="sd:AlertType"/>
	<complexType name="ShipPosType">
		<sequence>
			<element name="shipId" type="int" minOccurs="1" maxOccurs="1"/>
			<element name="seq" type="int" minOccurs="1" maxOccurs="1"/>
			<element name="lat" type="double" minOccurs="1" maxOccurs="1"/>
			<element name="lon" type="double" minOccurs="1" maxOccurs="1"/>
			<element name="info" type="string" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>
	<complexType name="ShipPositions">
		<sequence>
			<element name="ShipPos" maxOccurs="unbounded" type="sd:ShipPosType"/>
		</sequence>
	</complexType>
	<complexType name="AlertType">
		<sequence>
			<element name="ShipPos" type="sd:ShipPosType" minOccurs="1" maxOccurs="1"/>
			<element name="AlertMessage" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="AlertSeverity" type="int" minOccurs="1" maxOccurs="1"/>
			<element name="AlertDateTime" type="dateTime" minOccurs="1" maxOccurs="1"/>
		</sequence>
	</complexType>
</schema>

=== paullewallencom/oracle-978-1-8496-8454-5/_/Chapter 3/OCEPBook_Ch03_Spatial_EclipseProjects/com.oracle.cep.spatial.book.jaxb/schemas/shipdemo.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:ShipPosList xmlns:sd="http://xmlns.oracle.com/ns/spatialdemo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.oracle.com/ns/spatialdemo shipdemo.xsd ">
  <sd:ShipPos>
    <sd:shipId>102345</sd:shipId>
    <sd:seq>1</sd:seq>
    <sd:lat>47.564797356181465</sd:lat>
    <sd:lon>-52.701759338378906</sd:lon>
    <sd:info>CDN</sd:info>
  </sd:ShipPos>
  <sd:ShipPos>
    <sd:shipId>102345</sd:shipId>
    <sd:seq>2</sd:seq>
    <sd:lat>45.4578</sd:lat>
    <sd:lon>-50.1234</sd:lon>
    <sd:info>CDN</sd:info>
  </sd:ShipPos>
  <sd:ShipPos>
    <sd:shipId>102345</sd:shipId>
    <sd:seq>3</sd:seq>
    <sd:lat>45.6578</sd:lat>
    <sd:lon>-49.1234</sd:lon>
    <sd:info>CDN</sd:info>
  </sd:ShipPos>      
</sd:ShipPosList>
